In [13]:
import numpy
numpy.__version__

'1.24.3'

In [12]:
pip install numpy

^C
Note: you may need to restart the kernel to use updated packages.


In [18]:
v = np.arange(10,21)
print(v)

[10 11 12 13 14 15 16 17 18 19 20]


In [38]:
v = np.arange(21)
v = v[21:9:-1]
print(v)

[20 19 18 17 16 15 14 13 12 11 10]


In [44]:
x2 = np.arange(4).reshape(2,2)
print(x2)

[[0 1]
 [2 3]]


In [46]:
x4 = np.random.randint(10, size = (4,4,4))
print(x4)

[[[1 9 6 1]
  [8 5 8 8]
  [6 8 0 7]
  [0 4 7 4]]

 [[6 7 9 1]
  [5 3 4 6]
  [9 6 6 6]
  [4 4 9 6]]

 [[7 0 1 3]
  [5 2 8 3]
  [9 7 8 5]
  [1 4 4 3]]

 [[4 0 1 6]
  [4 0 0 8]
  [4 0 6 7]
  [8 0 9 3]]]


In [94]:
x3 = np.random.randint(10, size = (3,3))
print(x3)

x3.min()
print(f"min: {min} ")

x3.max()
print(f"max: {max} ")

[[3 7 3]
 [6 2 6]
 [3 2 4]]
min: 0 
max: 9 


In [76]:
x = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [143]:
x = np.random.randint(-10,10,7)
print(x)

print()
print(abs(x))

print()
x[x.argmax()]=0
print(abs(x))

[ 7  8  0 -8  1 -5  2]

[7 8 0 8 1 5 2]

[7 0 0 8 1 5 2]


In [158]:
x = np.random.randint(10, size=(4,4))
print(x)
print()

print(x[:2,:3])
print()

print(x[:4,::2])

[[2 7 8 6]
 [9 6 3 2]
 [0 8 9 4]
 [8 7 2 5]]

[[2 7 8]
 [9 6 3]]

[[2 8]
 [9 3]
 [0 9]
 [8 2]]


In [169]:
x=np.random.randint(10, size=(3,3))
x2=np.random.randint(10, size=(3,3))
print(x)
print()

print(x2)
print()

vert=np.concatenate([x, x2])
print(vert)
print()

horiz=np.concatenate([x, x2], axis=1)
print(horiz)
print()

vertikal=np.vstack([x, x2])
print(vertikal)
print()

horizontal=np.hstack([x, x2])
print(horizontal)

[[9 4 8]
 [1 5 5]
 [1 5 3]]

[[1 4 4]
 [9 8 9]
 [9 3 7]]

[[9 4 8]
 [1 5 5]
 [1 5 3]
 [1 4 4]
 [9 8 9]
 [9 3 7]]

[[9 4 8 1 4 4]
 [1 5 5 9 8 9]
 [1 5 3 9 3 7]]

[[9 4 8]
 [1 5 5]
 [1 5 3]
 [1 4 4]
 [9 8 9]
 [9 3 7]]

[[9 4 8 1 4 4]
 [1 5 5 9 8 9]
 [1 5 3 9 3 7]]


In [184]:
a=np.random.randint(10, size=(6,6))
print(a)
print()

b=np.vsplit(a,2)
print(b)
print()

c=np.hsplit(a,2)
print(c)


[[1 0 6 3 7 1]
 [6 2 7 9 0 6]
 [0 4 6 3 4 9]
 [2 3 3 9 9 5]
 [9 1 6 1 1 6]
 [8 9 6 6 8 6]]

[array([[1, 0, 6, 3, 7, 1],
       [6, 2, 7, 9, 0, 6],
       [0, 4, 6, 3, 4, 9]]), array([[2, 3, 3, 9, 9, 5],
       [9, 1, 6, 1, 1, 6],
       [8, 9, 6, 6, 8, 6]])]

[array([[1, 0, 6],
       [6, 2, 7],
       [0, 4, 6],
       [2, 3, 3],
       [9, 1, 6],
       [8, 9, 6]]), array([[3, 7, 1],
       [9, 0, 6],
       [3, 4, 9],
       [9, 9, 5],
       [1, 1, 6],
       [6, 8, 6]])]
