In [3]:
try:
    print(2/0)
except ZeroDivisionError:
    print("Нелья делить на ноль")

Нелья делить на ноль


In [5]:
print("Простой калькулатор")
print("Команда позволить остановить работу\n")

while True:
    first_number = input("Введите первое число: ")
    if first_number == 'quit':
        break
        
    second_number = input("Введите второе число: ")
    if second_number == 'quit':
        break
     
    try:
        answer = int(first_number)/int(second_number)
    
    except:
        print("Нелья делить на ноль")
        
    else:
        print(answer)
        print("Hello\n")

Простой калькулатор
Команда позволить остановить работу

Введите первое число: 5
Введите второе число: 2
2.5
Hello

Введите первое число: 2
Введите второе число: 0,
Нелья делить на ноль
Введите первое число: quit


In [12]:
filename = 'usd.txt'

try:
    with open(filename) as p:
        contents_0 = p.read()   
    print(contents_0)
    
except: 
    print("Net takogo fayla")

Net takogo fayla


In [13]:
import numpy
numpy.__version__

'1.24.3'

In [14]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

x1 = np.random.randint(10, size = 6)
x2 = np.random.randint(10, size = (3,4))
x3 = np.random.randint(10, size = (3,4,5))

print(x1)
print()
print(x2)
print()
print(x3)
print()

[7 0 4 4 8 2]

[[6 4 9 6]
 [8 7 0 8]
 [4 2 9 3]]

[[[4 5 7 0 2]
  [0 4 8 4 1]
  [7 9 0 8 8]
  [6 6 7 2 3]]

 [[4 3 6 7 4]
  [4 7 4 2 1]
  [8 5 8 7 4]
  [9 7 6 7 0]]

 [[8 6 8 4 8]
  [2 3 6 4 2]
  [2 1 6 9 6]
  [4 2 5 4 4]]]



In [26]:
print(x3.shape)

(3, 4, 5)


In [27]:
print(x3.size)

60


In [29]:
print(x3.dtype)

int32


In [33]:
print(x1[2])

3


In [40]:
print(x2[2,1])

0


In [41]:
print(x2)

[[1 5 0 1]
 [3 2 2 2]
 [1 0 3 4]]


In [43]:
x2[2,1]=7
print(x2)

[[1 5 0 1]
 [3 2 2 2]
 [1 7 3 4]]


In [45]:
#x[начало:конец:шаг]
x=np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [52]:
print(x[:5])
print(x[1:5])
print(x[0:10:3])
print(x[1::2])
print(x[::2])

[0 1 2 3 4]
[1 2 3 4]
[0 3 6 9]
[1 3 5 7 9]
[0 2 4 6 8]


In [53]:
print(x2)

[[1 5 0 1]
 [3 2 2 2]
 [1 7 3 4]]


In [56]:
print(x2[:2,:3])

[[1 5 0]
 [3 2 2]]


In [57]:
print(x2[:3,::2])

[[1 0]
 [3 2]
 [1 3]]


In [6]:
x2_srez = x2[:2,:2]
print(x2_srez)
print(x2)

[[6 4]
 [8 7]]
[[6 4 9 6]
 [8 7 0 8]
 [4 2 9 3]]


In [7]:
x2_srez[0,0]=15
print(x2_srez)
print(x2)

[[15  4]
 [ 8  7]]
[[15  4  9  6]
 [ 8  7  0  8]
 [ 4  2  9  3]]


In [10]:
x2_copy = x2[:2,:2].copy()
x2_copy[0,0]=1
print(x2_copy)
print(x2)

[[1 4]
 [8 7]]
[[0 4 9 6]
 [8 7 0 8]
 [4 2 9 3]]


In [11]:
tabl = np.arange(1,10)
print(tabl)

[1 2 3 4 5 6 7 8 9]


In [12]:
tabl = np.arange(1,10).reshape((3,3))
print(tabl)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
x = np.array ([1,2,3])
print(x)

[1 2 3]


In [16]:
x.reshape(1,3)
x

array([1, 2, 3])

In [17]:
x[np.newaxis, :]
x

array([1, 2, 3])

In [18]:
print(x)

[1 2 3]


In [19]:
x.reshape([3,1])

array([[1],
       [2],
       [3]])

In [22]:
x[:, np.newaxis]
x

array([1, 2, 3])

In [25]:
x = np.array([1,2,3])
y = np.array([9,8,7])

np.concatenate([x,y])

array([1, 2, 3, 9, 8, 7])

In [37]:
dvuh = np.array([[1,2,3], [4,5,6]])
dvuh_2 = np.array([[7,8,9], [4,5,6]])
np.concatenate([dvuh, dvuh_2])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [4, 5, 6]])

In [38]:
np.concatenate([dvuh, dvuh_2], axis=1)

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 4, 5, 6]])

In [39]:
x = np.array([1,2,3])
np.vstack([x, dvuh])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [41]:
np.hstack([dvuh, dvuh_2])

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 4, 5, 6]])

In [44]:
x = np.array([1,2,3,4,5,6,7,8,9])
x1, x2, x3 = np.split(x, [3,4])

print(x1)
print(x2)
print(x3)

[1 2 3]
[4]
[5 6 7 8 9]


In [45]:
kvadrat = np.arange(16).reshape([4,4])
print(kvadrat)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
